Repository Medici-Mansion/shinnyang-front, pull requests merged in 2023-12, with the labels that each got.

#8 0.0.9
  app/(root)/(home)/[userId]/layout.tsx
  app/(root)/(home)/[userId]/nickname/page.tsx
  app/(root)/(home)/[userId]/post/[letterId]/page.tsx
  app/(root)/(home)/[userId]/post/page.tsx
  app/(root)/(route)/layout.tsx
  app/(root)/(route)/page.tsx
  app/globals.css
  app/layout.tsx
  bun.lockb
  components/reply.tsx
  components/ui/button.tsx
  components/ui/input.tsx
  package-lock.json
  package.json
  public/bg-shinnyang.png
  public/cat.png
  tailwind.config.ts
Labels: 🔍 QA, 🎨 [CLIENT]

#12 [SNP-55] 회원/비회원 편지 보내기 화면 제작
  app/(root)/(home)/[userId]/nickname/page.tsx
  app/(root)/(home)/[userId]/post/page.tsx
  app/(root)/(home)/layout.tsx
  app/(root)/(home)/letter/page.tsx
  app/(root)/(home)/letter/template.tsx
  app/(root)/(route)/page.tsx
  app/globals.css
  app/layout.tsx
  components/pages/letter/finish-letter.tsx
  components/pages/letter/mailing.tsx
  components/pages/letter/select-pad.tsx
  components/pages/letter/write-letter.tsx
  components/provider/query-provider.tsx
  components/textarea.tsx
  components/ui/form.tsx
  components/ui/input.tsx
  components/ui/label.tsx
  components/ui/radio-group.tsx
  hooks/use-hash-router.tsx
  hydrate/get-query-client.ts
  hydrate/prefetch-query.tsx
  layout/base-layout.tsx
  package-lock.json
  package.json
  public/cat_1.png
  public/cat_2.png
  public/cat_3.png
  public/letter_sheet.png
Labels: 🔍 QA, 🎨 [CLIENT]

#15 Feature: 유저 정보 불러오기
  app/(root)/(route)/auth/page.tsx
  package-lock.json
  package.json
Labels: 🔍 QA, 🎨 [CLIENT]

#14 [SNP-56] 반응형 레이아웃/공통 컴포넌트 적용
  .prettierrc
  app/(root)/(home)/[userId]/layout.tsx
  app/(root)/(home)/[userId]/nickname/page.tsx
  app/(root)/(home)/[userId]/post/[letterId]/page.tsx
  app/(root)/(home)/[userId]/post/page.tsx
  app/(root)/(home)/layout.tsx
  app/(root)/(home)/letter/page.tsx
  app/(root)/(home)/letter/template.tsx
  app/(root)/(route)/auth/page.tsx
  app/(root)/(route)/layout.tsx
  app/(root)/(route)/page.tsx
  app/globals.css
  app/layout.tsx
  components/layout.tsx
  components/pages/letter/finish-letter.tsx
  components/pages/letter/mailing.tsx
  components/pages/letter/select-pad.tsx
  components/pages/letter/write-letter.tsx
  components/provider/query-provider.tsx
  components/reply.tsx
  components/textarea.tsx
  components/ui/button.tsx
  components/ui/form.tsx
  components/ui/input.tsx
  components/ui/label.tsx
  components/ui/radio-group.tsx
  hooks/use-hash-router.tsx
  hydrate/get-query-client.ts
  hydrate/prefetch-query.tsx
  layout/base-layout.tsx
  package-lock.json
  package.json
  public/bg-shinnyang copy.png
  public/cat_1.png
  public/cat_2.png
  public/cat_3.png
  public/letter_sheet.png
  tailwind.config.ts
Labels: 🎨 [CLIENT]

#21 [SNP-64] Google 로그인 연동
  .gitignore
  apis/index.ts
  app/(root)/(home)/[userId]/nickname/page.tsx
  app/(root)/(route)/page.tsx
  app/api/auth/[serviceName]/route.ts
  app/layout.tsx
  app/not-found.tsx
  components/pages/error.tsx
  components/pages/loading.tsx
  components/provider/session-provider.tsx
  components/provider/user-provider.tsx
  env.d.ts
  global.d.ts
  hooks/use-set-nickname.tsx
  middleware.ts
  package-lock.json
  package.json
  store/user.ts
  tailwind.config.ts
  type.ts
Labels: 🔍 QA, 🎨 [CLIENT]

#23 Feature: [SNP-74] 공통코드 제작
  apis/index.ts
  app/(root)/(home)/[userId]/layout.tsx
  app/(root)/(home)/[userId]/post/page.tsx
  app/(root)/(home)/letter/page.tsx
  app/(root)/(route)/page.tsx
  app/globals.css
  app/layout.tsx
  components/pages/letter/select-pad.tsx
  components/pages/post/cat-buttons.tsx
  components/pages/post/post-box.tsx
  lib/queries/common.query.ts
  next.config.js
  tailwind.config.ts
  type.ts
Labels: 🎨 [CLIENT]

#26 [CLIENT] [SNP-75] 편지쓰기 구현
  apis/index.ts
  app/(root)/(home)/[userId]/layout.tsx
  app/(root)/(home)/[userId]/letter/page.tsx
  app/(root)/(home)/[userId]/letter/template.tsx
  app/(root)/(home)/[userId]/post/page.tsx
  app/(root)/(home)/layout.tsx
  app/(root)/(route)/page.tsx
  app/(root)/layout.tsx
  app/error.tsx
  app/layout.tsx
  components/pages/letter/finish-letter.tsx
  components/pages/letter/select-pad.tsx
  components/pages/letter/write-letter.tsx
  components/provider/session-provider.tsx
  form-state.ts
  hooks/use-hash-router.tsx
  hooks/use-send-letter.tsx
  package-lock.json
  type.ts
Labels: ✅ 완료, 🎨 [CLIENT]
